package project;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author barry
 */
public class BioMarkingSchemeGUI extends javax.swing.JFrame {
    
    private final ArrayList <BioMarkingScheme> aList;
   
    private int gradeA, gradeB, gradeC, year;
    private final int sumA, sumB, sumC;
    
    private int count;

    /**
     * Creates new form BioMarkingSchemeGUI
     */
    public BioMarkingSchemeGUI() {
        initComponents();
        
         
        //initialise variables
        aList = new ArrayList<>();
        
        gradeA = 0;
        gradeB = 0;
        gradeC = 0;
        year = 0;
        count = 0;
        sumA = gradeA /50 * 100;
        sumB = gradeB /60 * 100;
        sumC = gradeC /240 * 100;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnViewSaved = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 472, 80, 29);

        btnSubmit.setText("Submit Answers");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(189, 436, 130, 30);

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay);
        btnDisplay.setBounds(190, 480, 130, 30);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Biology Marking Scheme");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(123, 11, 227, 21);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Enter year of exam paper:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 88, 128, 14);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Enter Section A marks (out of 100):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 185, 175, 14);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Enter Section B marks (out of 60):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 283, 169, 14);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Enter Section C marks (out of 240):");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 381, 175, 14);

        TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF4ActionPerformed(evt);
            }
        });
        getContentPane().add(TF4);
        TF4.setBounds(232, 85, 180, 30);
        getContentPane().add(TF1);
        TF1.setBounds(232, 172, 180, 30);
        getContentPane().add(TF2);
        TF2.setBounds(232, 280, 180, 30);
        getContentPane().add(TF3);
        TF3.setBounds(232, 368, 180, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(337, 436, 120, 30);

        btnViewSaved.setText("View Saved");
        btnViewSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavedActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewSaved);
        btnViewSaved.setBounds(340, 480, 120, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/bioBG.jpg"))); // NOI18N
        background.setText("jLabel6");
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         dispose();
        new LcBio ().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //getting text from texfields
        year = Integer.parseInt(TF4.getText());
        gradeA = Integer.parseInt(TF1.getText());
        gradeB = Integer.parseInt(TF2.getText());
        gradeC = Integer.parseInt(TF3.getText());
        
        
        BioMarkingScheme a = new BioMarkingScheme();
        
        a.setYear(year);
        a.setGradeA(gradeA);
        a.setGradeB(gradeB);
        a.setGradeC(gradeC);
        
        
        //adding object to ArrayList
        aList.add(a);
        
        count++;
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
         //loop
        for (int i = 0; i < aList.size(); i = 1 + 1) {
    
        JOptionPane.showMessageDialog(null, "Year: " + aList.get(i).getYear() 
                + "\n Section A percentage : " + aList.get(i).getGradeA() / 100 * 100 + "%"
                + 
                 "\n Section B percentage : " + aList.get(i).getGradeB() / 60 * 100 + "%"
                
                + " \n Section C marks : " + aList.get(i).getGradeC() / 240 * 100 + "%"
                
        );
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
        
     //File handling is here, Liam look at this - it is similar to what you will need 
        
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try {
            outFile = new File ("input.txt");
            fStream = new FileOutputStream (outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            JOptionPane.showMessageDialog(null,"File saved successfully");
            
            oStream.close();
            }
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavedActionPerformed
        // TODO add your handling code here:
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        
        try {
            inFile = new File ("input.txt");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream (fStream);
            
            
            
            ArrayList <BioMarkingScheme> xList;
            xList = (ArrayList<BioMarkingScheme>)oStream.readObject();
            oStream.close();
            
            
            
           for( BioMarkingScheme x : xList) {
           JOptionPane.showMessageDialog(null,"Year: " + x.getYear() +"\n" + " SectionA: " + x.getGradeA()+ "\n"+ " SectionB: " + x.getGradeB() + "\n" + " SectionC: " + x.getGradeC());           
        } 
        }
        
        catch (IOException e){
            System.out.println(e);
        }
        
        catch(ClassNotFoundException ex){
            System.out.println(ex);}
        
        
        
    }//GEN-LAST:event_btnViewSavedActionPerformed

    private void TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF4ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_TF4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioMarkingSchemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioMarkingSchemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioMarkingSchemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioMarkingSchemeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioMarkingSchemeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewSaved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
