package project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author barry
 */
public class BioModuleDescriptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form BioModuleDescriptionGUI
     */
    public BioModuleDescriptionGUI() {
        initComponents();
        
        ModuleDescription myMD = new ModuleDescription();
        myMD.setName("Leaving Certificate Biology");
       myMD.setDuration("2 Years");
       myMD.setDescription("<html>The structure of this description reflects the examination format of the Leaving Certificate Biology syllabus."
+ " \n \n \n \n Examination format: \n"
+ " \n Section A: 100 marks 25% of the Examination."
+ " \n There are six questions in this section, you will be marked on your best five. Each question is worth 20 marks."
+ " \n Section B: 60 marks 15% of the Examination."
+ " \n There are two questions on this section, which is centred on the mandatory practical activities along with the use and handling of experimental data. These are worth 30 maks each."
+ "\n Section C: 240 marks 60% of the Examination. "
+ "\n There are six questions in this section, you will be marked on your best four. Each question is worth 60 marks."
+ "\n Divided to 3 sections. Unit 1, 2 and three. "
+ "\n Unit 1: Chapters 1-6 and Mandatory Practical Activities 1-5."
+ "\n Unit 2: Chapters 7-15 and Mandatory Practical Activities 6-14."
+ "\n Unit 3: Chapters 16-38 and Mandatory Practical Activities 15-23. </html> "
               
       );
       
       
       lblName.setText(myMD.getName());
       lblDur.setText(myMD.getDuration());
       lblDes.setText(myMD.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblDur = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lbldur = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Module Description");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 24, 181, 21);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Module Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 88, 71, 14);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Duration:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 163, 47, 14);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Module Description:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 253, 98, 14);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 600, 90, 29);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(148, 253, 0, 14);

        lblDes.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblDes.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(lblDes);
        lblDes.setBounds(154, 249, 396, 355);
        getContentPane().add(lblDur);
        lblDur.setBounds(369, 163, 193, 0);

        lblName.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(lblName);
        lblName.setBounds(148, 88, 193, 14);

        lbldur.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(lbldur);
        lbldur.setBounds(148, 163, 215, 14);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(0, 20, 80, 29);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/bioBG.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         dispose();
        new LcBio ().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
         dispose();
        new GUI ().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioModuleDescriptionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblDur;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbldur;
    // End of variables declaration//GEN-END:variables
}
