/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
/**
 *
 * @author barry
 */
public class BioQuizGUI extends javax.swing.JFrame {

    String question1;
    String question2;
    String question3;
    
    ArrayList <BioQuiz> arr;
    
    //counter for the loop
    int count;
    
    
    
    
    /**
     * Creates new form BioQuizGUI
     */
    public BioQuizGUI() {
        initComponents();
        
        
        arr = new ArrayList();
        
        // initialising count
        count = 0;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        btnDisplay = new javax.swing.JToggleButton();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        btnSave = new javax.swing.JToggleButton();
        btnViewSaved = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Biology Quiz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(179, 11, 116, 21);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("1. What pigmant is most responsible for photosynthesis?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 323, 14);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("2. What does the 'm' statnd for in mRNA?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 230, 236, 14);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("3. What is the position an animal occupies on a food chain called?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 410, 375, 25);

        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });
        getContentPane().add(TF1);
        TF1.setBounds(60, 140, 380, 30);
        getContentPane().add(TF2);
        TF2.setBounds(60, 310, 380, 30);

        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        getContentPane().add(TF3);
        TF3.setBounds(60, 490, 380, 30);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(0, 0, 100, 25);

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay);
        btnDisplay.setBounds(360, 620, 100, 25);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(360, 570, 100, 25);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 620, 80, 25);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(480, 570, 90, 25);

        btnViewSaved.setText("View Saved");
        btnViewSaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavedActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewSaved);
        btnViewSaved.setBounds(480, 620, 100, 25);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/bioBG.jpg"))); // NOI18N
        background.setText("jLabel5");
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        BioQuiz a;
        a = new BioQuiz();
        
        question1 = TF1.getText();
        question2 = TF2.getText();
        question3 = TF3.getText();
        
        
        
        a.setQ1(question1);
        a.setQ2(question2);
        a.setQ3(question3);
        
        
        //adding object to array
        arr.add(a);
        //count++;
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < arr.size(); i = i + 1) {
             JOptionPane.showMessageDialog(null,"Your answer for question 1: " +arr.get(i).getQ1() + "\n Correct answer: Chlorophyll" + "\n Your answer for question 2: " + arr.get(i).getQ2() + "\n Correct Answer: Memory"+ "\n Your answer for question 3: " +arr.get(i).getQ3() + "\n Correct answer: Trophic Level" );
        }
            
            
        
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
         new LcBio ().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
         new GUI ().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// TODO add your handling code here:       
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try {
            outFile = new File ("input.txt");
            fStream = new FileOutputStream (outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(arr);
            oStream.close();
            JOptionPane.showMessageDialog(null,"File saved successfully");
            
            
            }
        catch (IOException e) {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewSavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavedActionPerformed
        // TODO add your handling code here:
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        
        try {
            inFile = new File ("input.txt");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream (fStream);
            
            ArrayList<BioQuiz> arr;
            arr = (ArrayList<BioQuiz>) oStream.readObject();
            oStream.close();
           for (int i = 0; i < arr.size(); i = i + 1) {
           JOptionPane.showMessageDialog(null, "Answer 1: "  +arr.get(i).getQ1() +"\n Answer 2: " +arr.get(i).getQ2() + "\n Answer 3: " +arr.get(i).getQ3()); 
           }
        }
                     
        catch(IOException e){
            System.out.println(e);
        }
        
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
                   
                 
    }//GEN-LAST:event_btnViewSavedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JLabel background;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnDisplay;
    private javax.swing.JButton btnHome;
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewSaved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
