/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author x14426302
 */
public class GUI extends javax.swing.JFrame {
   

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcSciBtn = new javax.swing.JButton();
        lcBioBtn = new javax.swing.JButton();
        lcPhyBtn = new javax.swing.JButton();
        lcChemBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        jcSciBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jcSciBtn.setText("Junior Cert Science");
        jcSciBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSciBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jcSciBtn);
        jcSciBtn.setBounds(190, 120, 222, 90);

        lcBioBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lcBioBtn.setText("Leaving Cert Biology");
        lcBioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lcBioBtn);
        lcBioBtn.setBounds(190, 230, 222, 90);

        lcPhyBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lcPhyBtn.setText("Leaving Cert Physics");
        lcPhyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcPhyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lcPhyBtn);
        lcPhyBtn.setBounds(190, 340, 222, 90);

        lcChemBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lcChemBtn.setText("Leaving Cert Chemistry");
        lcChemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcChemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lcChemBtn);
        lcChemBtn.setBounds(190, 450, 222, 90);

        titleLbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Science Application");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(220, 40, 155, 21);

        bgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/guiBG.jpg"))); // NOI18N
        getContentPane().add(bgLbl);
        bgLbl.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lcChemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcChemBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChem().setVisible(true); 
    }//GEN-LAST:event_lcChemBtnActionPerformed

    private void lcBioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBioBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcBio().setVisible(true);
    }//GEN-LAST:event_lcBioBtnActionPerformed

    private void lcPhyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcPhyBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyOption().setVisible(true);
    }//GEN-LAST:event_lcPhyBtnActionPerformed

    private void jcSciBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSciBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new JcScience().setVisible(true);
    }//GEN-LAST:event_jcSciBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLbl;
    private javax.swing.JButton jcSciBtn;
    private javax.swing.JButton lcBioBtn;
    private javax.swing.JButton lcChemBtn;
    private javax.swing.JButton lcPhyBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
