package project;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author barry
 */
public class LcBio extends javax.swing.JFrame {

    /**
     * Creates new form BiologyHigher
     */
    public LcBio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btnMD = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(240, 240, 240));
        Title.setText("Leaving Cert Biology");
        getContentPane().add(Title);
        Title.setBounds(220, 20, 165, 21);

        btnMD.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnMD.setText("Module Description");
        btnMD.setPreferredSize(new java.awt.Dimension(140, 40));
        btnMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDActionPerformed(evt);
            }
        });
        getContentPane().add(btnMD);
        btnMD.setBounds(220, 150, 156, 40);

        btnMS.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnMS.setText("Marking Scheme");
        btnMS.setPreferredSize(new java.awt.Dimension(140, 40));
        btnMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSActionPerformed(evt);
            }
        });
        getContentPane().add(btnMS);
        btnMS.setBounds(220, 230, 156, 40);

        btnQuiz.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnQuiz.setText("Quiz");
        btnQuiz.setPreferredSize(new java.awt.Dimension(140, 40));
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuiz);
        btnQuiz.setBounds(220, 320, 156, 40);

        btnExp.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btnExp.setText("Experiments");
        btnExp.setPreferredSize(new java.awt.Dimension(140, 40));
        btnExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpActionPerformed(evt);
            }
        });
        getContentPane().add(btnExp);
        btnExp.setBounds(220, 400, 156, 40);

        jButton1.setText("<- Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 480, 100, 25);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/bioBG.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSActionPerformed
        // TODO add your handling code here:
        dispose();
        dispose();
        new BioMarkingSchemeGUI().setVisible(true);
    }//GEN-LAST:event_btnMSActionPerformed

    private void btnMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDActionPerformed
        // TODO add your handling code here:
        dispose();
        new BioModuleDescriptionGUI ().setVisible(true);
    }//GEN-LAST:event_btnMDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI ().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        // TODO add your handling code here:
        dispose();
         new BioQuizGUI ().setVisible(true);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpActionPerformed
        // TODO add your handling code here:
        dispose();
         new BioExperimentGUI ().setVisible(true);
    }//GEN-LAST:event_btnExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcBio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LcBio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnMD;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
