/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author Evan
 */
public class LcChemMD extends javax.swing.JFrame {
    ArrayList <ModuleDescription> aListMD = new ArrayList<>();
    /**
     * Creates new form lcChemMD
     */
    public LcChemMD() {
        initComponents();
        ModuleDescription md = new ModuleDescription();
        md.setName("Leaving Certificate Chemistry");
        md.setDescription("<html>Leaving Cert Chemistry is comprised of all the essential and relevant topics within general chemistry. The major topics involved include the following:\n" +
"\n" +
"Atomic structure\n" +
"Volumetric analysis\n" +
"Organic chemistry\n" +
"Water chemistry\n" +
"Reaction mechanisms.\n" +
"There also is an option to be taken as part of the course which involves the study of atmospheric and industrial chemistry or the study of materials and electrochemistry.\n" +
"\n" +
"Experimental investigations are an essential part of the leaving certificate course. Each student must complete at least 28 experiments over the duration of the course.\n" +
"\n" +
"Experimental work is examined as part of the leaving cert exam and forms the basis for a minimum of three questions on the exam paper.</html>");
        md.setDuration("2 Years");
        aListMD.add(md);
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("chemMD.txt");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(aListMD);
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }
        
        File inFile;
        FileInputStream ffStream;
        ObjectInputStream ooStream;
        try {
            inFile = new File("chemMD.txt");
            ffStream = new FileInputStream(inFile);
            ooStream = new ObjectInputStream(ffStream);

            ArrayList<ModuleDescription> aListMD;
            aListMD = (ArrayList<ModuleDescription>) ooStream.readObject();
            ooStream.close();
            
            for(ModuleDescription m:aListMD){
                modNameLbl.setText(m.getName());
                mdDescLbl.setText(m.getDescription());
                showDurLbl.setText(m.getDuration());
            }

        } catch (IOException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        
        
        
        
//        for(int i=0; i<aListMD.size();i++){
//            modNameLbl.setText(aListMD.get(i).getName());
//            mdDescLbl.setText(aListMD.get(i).getDescription());
//            showDurLbl.setText(aListMD.get(i).getDuration());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdTitleLbl = new javax.swing.JLabel();
        modLbl = new javax.swing.JLabel();
        modDescLbl = new javax.swing.JLabel();
        modNameLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        mdDescLbl = new javax.swing.JLabel();
        durLbl = new javax.swing.JLabel();
        showDurLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        mdTitleLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        mdTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        mdTitleLbl.setText("Module Description");
        getContentPane().add(mdTitleLbl);
        mdTitleLbl.setBounds(180, 20, 230, 28);

        modLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        modLbl.setForeground(new java.awt.Color(255, 255, 255));
        modLbl.setText("Module Name:");
        getContentPane().add(modLbl);
        modLbl.setBounds(40, 80, 110, 17);

        modDescLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        modDescLbl.setForeground(new java.awt.Color(255, 255, 255));
        modDescLbl.setText("Module Desciption:");
        getContentPane().add(modDescLbl);
        modDescLbl.setBounds(40, 140, 130, 17);

        modNameLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        modNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(modNameLbl);
        modNameLbl.setBounds(163, 80, 290, 20);

        backBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backBtn.setText("<--  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(40, 560, 100, 29);

        mdDescLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        mdDescLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mdDescLbl);
        mdDescLbl.setBounds(160, 180, 295, 304);

        durLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        durLbl.setForeground(new java.awt.Color(255, 255, 255));
        durLbl.setText("Duration:");
        getContentPane().add(durLbl);
        durLbl.setBounds(40, 110, 60, 17);

        showDurLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        showDurLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(showDurLbl);
        showDurLbl.setBounds(167, 110, 290, 20);

        bgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/chemBG.jpg"))); // NOI18N
        getContentPane().add(bgLbl);
        bgLbl.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChem().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the NimbusmdDescnd feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcChemMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcChemMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcChemMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcChemMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcChemMD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JLabel durLbl;
    private javax.swing.JLabel mdDescLbl;
    private javax.swing.JLabel mdTitleLbl;
    private javax.swing.JLabel modDescLbl;
    private javax.swing.JLabel modLbl;
    private javax.swing.JLabel modNameLbl;
    private javax.swing.JLabel showDurLbl;
    // End of variables declaration//GEN-END:variables
}
