/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author Evan
 */
public class LcChemMS extends javax.swing.JFrame {
    ArrayList <MarkingScheme> aListMS = new ArrayList();
    /**
     * Creates new form lcChemMS
     */
    public LcChemMS() {
        initComponents();
        MarkingScheme ms = new MarkingScheme();
        ms.setMarkA("All Questions are worth 50 Marks");
        ms.setTipsA("MUST answer atleast 2 Questions");
        ms.setTimeA("<html>Recommended time to spend on each question is 20 minutes, this will leave you with some spare time at the end of the exam to look back, as all questions carry equal marks, there is no need to focus on one particular section.</html>");
        ms.setMarkB("All Questions are worth 50 Marks");
        ms.setTipsB("MUST answer atleast 5 Questions");
        ms.setTimeB("<html>Recommended time to spend on each question is 20 minutes, this will leave you with some spare time at the end of the exam to look back, as all questions carry equal marks, there is no need to focus on one particular section.</html>");
        aListMS.add(ms);
        
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("chemMS.txt");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(aListMS);
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }
        
        File inFile;
        FileInputStream ffStream;
        ObjectInputStream ooStream;
        try {
            inFile = new File("chemMS.txt");
            ffStream = new FileInputStream(inFile);
            ooStream = new ObjectInputStream(ffStream);

            ArrayList<MarkingScheme> aListMS;
            aListMS = (ArrayList<MarkingScheme>) ooStream.readObject();
            ooStream.close();
            
            for(MarkingScheme m:aListMS){
                aMarkLbl.setText(m.getMarkA());
                aTipsLbl.setText(m.getTipsA());
                aTimingLbl.setText(m.getTimeA());
                bMarkLbl.setText(m.getMarkB());
                bTipsLbl.setText(m.getTipsB());
                bTimingLbl.setText(m.getTimeB());
            }

        } catch (IOException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        
        
//        for(int i=0; i<aListMS.size();i++){
//        aMarkLbl.setText(aListMS.get(i).getMarkA());
//        aTipsLbl.setText(aListMS.get(i).getTipsA());
//        aTimingLbl.setText(aListMS.get(i).getTimeA());
//        bMarkLbl.setText(aListMS.get(i).getMarkB());
//        bTipsLbl.setText(aListMS.get(i).getTipsB());
//        bTimingLbl.setText(aListMS.get(i).getTimeB());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msTitleLbl = new javax.swing.JLabel();
        sectALbl = new javax.swing.JLabel();
        secBLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        secAMarkLbl = new javax.swing.JLabel();
        secATipsLbl = new javax.swing.JLabel();
        secATimingLbl = new javax.swing.JLabel();
        secBMarkLbl = new javax.swing.JLabel();
        secBTipsLbl = new javax.swing.JLabel();
        secBTimingLbl = new javax.swing.JLabel();
        aMarkLbl = new javax.swing.JLabel();
        aTipsLbl = new javax.swing.JLabel();
        aTimingLbl = new javax.swing.JLabel();
        bMarkLbl = new javax.swing.JLabel();
        bTipsLbl = new javax.swing.JLabel();
        bTimingLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        msTitleLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        msTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        msTitleLbl.setText("Marking Scheme");
        getContentPane().add(msTitleLbl);
        msTitleLbl.setBounds(190, 20, 210, 28);

        sectALbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        sectALbl.setForeground(new java.awt.Color(255, 255, 255));
        sectALbl.setText("Section A:");
        getContentPane().add(sectALbl);
        sectALbl.setBounds(80, 70, 160, 17);

        secBLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secBLbl.setForeground(new java.awt.Color(255, 255, 255));
        secBLbl.setText("Section B:");
        getContentPane().add(secBLbl);
        secBLbl.setBounds(80, 350, 160, 17);

        backBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backBtn.setText("<--  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(80, 600, 200, 25);

        secAMarkLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secAMarkLbl.setForeground(new java.awt.Color(255, 255, 255));
        secAMarkLbl.setText("Mark:");
        getContentPane().add(secAMarkLbl);
        secAMarkLbl.setBounds(80, 110, 160, 32);

        secATipsLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secATipsLbl.setForeground(new java.awt.Color(255, 255, 255));
        secATipsLbl.setText("Tips:");
        getContentPane().add(secATipsLbl);
        secATipsLbl.setBounds(80, 160, 160, 28);

        secATimingLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secATimingLbl.setForeground(new java.awt.Color(255, 255, 255));
        secATimingLbl.setText("Timing:");
        getContentPane().add(secATimingLbl);
        secATimingLbl.setBounds(80, 210, 160, 17);

        secBMarkLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secBMarkLbl.setForeground(new java.awt.Color(255, 255, 255));
        secBMarkLbl.setText("Mark:");
        getContentPane().add(secBMarkLbl);
        secBMarkLbl.setBounds(80, 380, 160, 32);

        secBTipsLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secBTipsLbl.setForeground(new java.awt.Color(255, 255, 255));
        secBTipsLbl.setText("Tips:");
        getContentPane().add(secBTipsLbl);
        secBTipsLbl.setBounds(80, 420, 160, 28);

        secBTimingLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        secBTimingLbl.setForeground(new java.awt.Color(255, 255, 255));
        secBTimingLbl.setText("Timing:");
        getContentPane().add(secBTimingLbl);
        secBTimingLbl.setBounds(80, 470, 160, 17);

        aMarkLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(aMarkLbl);
        aMarkLbl.setBounds(160, 110, 300, 35);

        aTipsLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(aTipsLbl);
        aTipsLbl.setBounds(160, 160, 300, 30);

        aTimingLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(aTimingLbl);
        aTimingLbl.setBounds(160, 210, 300, 110);

        bMarkLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(bMarkLbl);
        bMarkLbl.setBounds(150, 380, 300, 32);

        bTipsLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(bTipsLbl);
        bTipsLbl.setBounds(150, 420, 300, 32);

        bTimingLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(bTimingLbl);
        bTimingLbl.setBounds(150, 470, 310, 115);

        bgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/chemBG.jpg"))); // NOI18N
        getContentPane().add(bgLbl);
        bgLbl.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChem().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcChemMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcChemMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcChemMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcChemMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcChemMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aMarkLbl;
    private javax.swing.JLabel aTimingLbl;
    private javax.swing.JLabel aTipsLbl;
    private javax.swing.JLabel bMarkLbl;
    private javax.swing.JLabel bTimingLbl;
    private javax.swing.JLabel bTipsLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JLabel msTitleLbl;
    private javax.swing.JLabel secAMarkLbl;
    private javax.swing.JLabel secATimingLbl;
    private javax.swing.JLabel secATipsLbl;
    private javax.swing.JLabel secBLbl;
    private javax.swing.JLabel secBMarkLbl;
    private javax.swing.JLabel secBTimingLbl;
    private javax.swing.JLabel secBTipsLbl;
    private javax.swing.JLabel sectALbl;
    // End of variables declaration//GEN-END:variables
}
