/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Evan
 */
public class LcChem extends javax.swing.JFrame {

    /**
     * Creates new form lcChem
     */
    public LcChem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        mdBtn = new javax.swing.JButton();
        msBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        expBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Leaving Cert Chemistry");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(150, 40, 270, 28);

        mdBtn.setText("Module Desciption");
        mdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mdBtn);
        mdBtn.setBounds(140, 140, 280, 80);

        msBtn.setText("Marking Scheme");
        msBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msBtnActionPerformed(evt);
            }
        });
        getContentPane().add(msBtn);
        msBtn.setBounds(140, 250, 280, 80);

        quizBtn.setText("Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quizBtn);
        quizBtn.setBounds(140, 360, 280, 80);

        expBtn.setText("Experiments");
        expBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expBtnActionPerformed(evt);
            }
        });
        getContentPane().add(expBtn);
        expBtn.setBounds(140, 470, 280, 70);

        backBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backBtn.setText("<--  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(40, 620, 100, 25);

        bgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/chemBG.jpg"))); // NOI18N
        getContentPane().add(bgLbl);
        bgLbl.setBounds(0, 0, 600, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChemExp().setVisible(true);
    }//GEN-LAST:event_expBtnActionPerformed

    private void mdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChemMD().setVisible(true);
    }//GEN-LAST:event_mdBtnActionPerformed

    private void msBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChemMS().setVisible(true);
    }//GEN-LAST:event_msBtnActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcChemQuiz().setVisible(true);
    }//GEN-LAST:event_quizBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcChem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcChem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcChem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcChem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcChem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JButton expBtn;
    private javax.swing.JButton mdBtn;
    private javax.swing.JButton msBtn;
    private javax.swing.JButton quizBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
