/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author caoimhemalone
 */
public class LcPhyQuizOL extends javax.swing.JFrame {
    String question, pQ, answer1, answer2, answer3, answer4, answer5, answer6, correctAnswer1, correctAnswer2, correctAnswer3, correctAnswer4, correctAnswer5, correctAnswer6;
    double resultPhy = 0.0;
    double markPhy = 0.0;
    
       ArrayList<Quiz> arrQ;
       ArrayList<Quiz> arrAns;
      
       
       
       
       
       
      

    /**
     * Creates new form Quiz
     */
    public LcPhyQuizOL() {
        initComponents();

        arrQ = new ArrayList<>();
        arrAns = new ArrayList<>();
       
        
        Quiz q1 = new Quiz();
        q1.setQuestion("<html>Question 1: \n Electric resistance is typically measured in what units?</html>");
        q1.setAnswer1("");
        arrQ.add(q1);
        
        Quiz q2 = new Quiz();
        q2.setQuestion("<html>Question 2: \n What is the first name of the famous scientist who gave us Newton’s three laws of motion? </html>");      
        q2.setAnswer2("");
        arrQ.add(q2);
        
        Quiz q3 = new Quiz();
        q3.setQuestion("<html> Question 3: \n True or false? Iron is attracted by magnets.</html>");
        q3.setAnswer3("");
        arrQ.add(q3);
        
        Quiz q4 = new Quiz();
        q4.setPQ("<html> Which picture shows the object which supplies the earth with the most energy? Type 'Picture+number' with no spaces</html>");
        q4.setAnswer4("");
        arrQ.add(q4);
        
        
        Quiz q5 = new Quiz();
        q5.setPQ("<html> Which picture shows the object that controls cycles? Type 'Picture+number' with no spaces </html>");
        q5.setAnswer5("");
        arrQ.add(q5);
        
        Quiz q6 = new Quiz();
        q6.setPQ("<html> Which picture shows the object that gives the earth the most light? Type 'Picture+number with no spaces' </html>");
        q6.setAnswer6("");
        arrQ.add(q6);
        
        
        
        bQQ1Lbl.setText(q1.getQuestion());
        bQQ2Lbl.setText(q2.getQuestion());
        bQQ3Lbl.setText(q3.getQuestion());
        
        pQQ1Lbl.setText(q4.getPQ());
        pQQ2Lbl.setText(q5.getPQ());
        pQQ3Lbl.setText(q6.getPQ());
        
        correctAnswer1 = "Ohms";
        correctAnswer2 = "Isaac";
        correctAnswer3 = "True";
        correctAnswer4 = "Picture1";
        correctAnswer5 = "Picture2";
        correctAnswer6 = "Picture1";
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        quiz = new javax.swing.JPanel();
        quizLbl = new javax.swing.JLabel();
        bQQ1Lbl = new javax.swing.JLabel();
        bQQ1TF = new javax.swing.JTextField();
        bQQ2Lbl = new javax.swing.JLabel();
        bQQ2TF = new javax.swing.JTextField();
        bQQ3Lbl = new javax.swing.JLabel();
        bQQ3TF = new javax.swing.JTextField();
        PicQueLbl = new javax.swing.JLabel();
        pQQ1Lbl = new javax.swing.JLabel();
        pQQ1TF = new javax.swing.JTextField();
        pQQ2Lbl = new javax.swing.JLabel();
        pQQ2TF = new javax.swing.JTextField();
        pQQ3Lbl = new javax.swing.JLabel();
        pQQ3TF = new javax.swing.JTextField();
        basicQuestionLbl = new javax.swing.JLabel();
        mCQ1Lbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        homeQuiz = new javax.swing.JButton();
        backQuiz = new javax.swing.JButton();
        pQImage1Lbl = new javax.swing.JLabel();
        pQImage2Lbl = new javax.swing.JLabel();
        pQImage3Lbl = new javax.swing.JLabel();
        pQImage4Lbl = new javax.swing.JLabel();
        bQa1Lbl = new javax.swing.JLabel();
        basicQuestionLbl1 = new javax.swing.JLabel();
        bQA2Lbl = new javax.swing.JLabel();
        bQA3Lbl = new javax.swing.JLabel();
        pic1Lbl = new javax.swing.JLabel();
        pic2Lbl = new javax.swing.JLabel();
        pic3Lbl = new javax.swing.JLabel();
        pic4Lbl = new javax.swing.JLabel();
        pQA1Lbl = new javax.swing.JLabel();
        pQA2Lbl = new javax.swing.JLabel();
        pQA3Lbl = new javax.swing.JLabel();
        expTitleLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 398));

        quiz.setBackground(new java.awt.Color(0, 0, 102));

        quizLbl.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        quizLbl.setForeground(new java.awt.Color(255, 255, 0));
        quizLbl.setText("Quiz");

        bQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ1Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ1TF.setPreferredSize(new java.awt.Dimension(171, 28));

        bQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ2Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ3Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQQ3TFActionPerformed(evt);
            }
        });

        PicQueLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        PicQueLbl.setForeground(new java.awt.Color(255, 255, 0));
        PicQueLbl.setText("Picture Question");

        pQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ1Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        pQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ2Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        pQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ3Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        basicQuestionLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        basicQuestionLbl.setForeground(new java.awt.Color(255, 255, 0));
        basicQuestionLbl.setText("Basic Question");

        mCQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(255, 255, 255));
        resetBtn.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        homeQuiz.setBackground(new java.awt.Color(255, 255, 255));
        homeQuiz.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        homeQuiz.setText("Home");
        homeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeQuizActionPerformed(evt);
            }
        });

        backQuiz.setBackground(new java.awt.Color(255, 255, 255));
        backQuiz.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        backQuiz.setText("<-- Back");
        backQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQuizActionPerformed(evt);
            }
        });

        pQImage1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sun.png"))); // NOI18N

        pQImage2Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/moon.png"))); // NOI18N

        pQImage3Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/fire.png"))); // NOI18N

        pQImage4Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/star.png"))); // NOI18N

        bQa1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQa1Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQa1Lbl.setText("Answer:");

        basicQuestionLbl1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        basicQuestionLbl1.setForeground(new java.awt.Color(255, 255, 0));
        basicQuestionLbl1.setText("Please give one word answers.");

        bQA2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQA2Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQA2Lbl.setText("Answer:");

        bQA3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQA3Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQA3Lbl.setText("Answer:");

        pic1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic1Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pic1Lbl.setText("Picture1");

        pic2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic2Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pic2Lbl.setText("Picture2");

        pic3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic3Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pic3Lbl.setText("Picture3");

        pic4Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic4Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pic4Lbl.setText("Picture4");

        pQA1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA1Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA1Lbl.setText("Answer:");

        pQA2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA2Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA2Lbl.setText("Answer:");

        pQA3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA3Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA3Lbl.setText("Answer:");

        expTitleLbl2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        expTitleLbl2.setForeground(new java.awt.Color(255, 255, 0));
        expTitleLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/ScienceAtom.png"))); // NOI18N

        javax.swing.GroupLayout quizLayout = new javax.swing.GroupLayout(quiz);
        quiz.setLayout(quizLayout);
        quizLayout.setHorizontalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addComponent(expTitleLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicQuestionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(basicQuestionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bQa1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(bQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(PicQueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(pQImage1Lbl)
                .addGap(47, 47, 47)
                .addComponent(pQImage2Lbl))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(pic3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(pic4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(pQImage3Lbl)
                .addGap(38, 38, 38)
                .addComponent(pQImage4Lbl))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pQA1Lbl)
                .addGap(18, 18, 18)
                .addComponent(pQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397)
                .addComponent(mCQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(quizLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(quizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        quizLayout.setVerticalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expTitleLbl2)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(homeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(backQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(quizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(basicQuestionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(basicQuestionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bQa1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(bQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(PicQueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pQImage1Lbl)
                    .addComponent(pQImage2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(pic4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pQImage3Lbl)
                    .addComponent(pQImage4Lbl))
                .addGap(61, 61, 61)
                .addComponent(pQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(pQA1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(mCQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(pQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(pQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(quiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQuizActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyOL().setVisible(true);
    }//GEN-LAST:event_backQuizActionPerformed

    private void homeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeQuizActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeQuizActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        bQQ1TF.setText("");
        bQQ2TF.setText("");
        bQQ3TF.setText("");

        pQQ1TF.setText("");
        pQQ2TF.setText("");
        pQQ3TF.setText("");

        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        answer1 = bQQ1TF.getText();
        answer2 = bQQ2TF.getText();
        answer3 = bQQ3TF.getText();
        answer4 = pQQ1TF.getText();
        answer5 = pQQ2TF.getText();
        answer6 = pQQ3TF.getText();
        
        Quiz q = new Quiz();
        
        q.setAnswer1(answer1);
        q.setAnswer2(answer2);
        q.setAnswer3(answer3);
        q.setAnswer4(answer4);
        q.setAnswer5(answer5);
        q.setAnswer6(answer6);
           
        q.setCorrectAnswer1(correctAnswer1);
        q.setCorrectAnswer2(correctAnswer2);
        q.setCorrectAnswer3(correctAnswer3);
        q.setCorrectAnswer4(correctAnswer5);
        q.setCorrectAnswer5(correctAnswer6);
        
       
        if(answer1.equalsIgnoreCase(correctAnswer1)){
           markPhy = markPhy +1;
       } 
       if(answer2.equalsIgnoreCase(correctAnswer2)){
           markPhy = markPhy +1;
       }
       if(answer3.equalsIgnoreCase(correctAnswer3)){
           markPhy = markPhy +1;
       } 
       if(answer4.equalsIgnoreCase(correctAnswer4)){
           markPhy = markPhy +1;
       } 
       if(answer5.equalsIgnoreCase(correctAnswer5)){
           markPhy = markPhy +1;
       } 
       if(answer6.equalsIgnoreCase(correctAnswer6)){
           markPhy = markPhy+1;
       }
       

       

        if(markPhy == 1){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy ==2){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 3){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 4){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 5){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 6){
            resultPhy = ((markPhy*100)/6);
        }
        
           
       
             dispose();
            new LcPhyHL().setVisible(true); 
                         File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("outputQuizOL.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(q);
            
            oStream.close();
        }
        
        catch(IOException e){
            System.out.println(e);
        }
        
        
        File inFile;
        FileInputStream fiStream;
        ObjectInputStream oiStream;
        
        try{
            inFile = new File("outputQuizOL.data");
            fiStream = new FileInputStream(inFile);
            oiStream = new ObjectInputStream(fiStream);
            
            
            Quiz qIO = (Quiz)oiStream.readObject();
            
             
        JOptionPane.showMessageDialog(null, "Your first answer is " +qIO.getAnswer1()+ ". The correct answer is "+correctAnswer1+".");
        JOptionPane.showMessageDialog(null, "Your second answer is " +qIO.getAnswer2()+". The correct answer is "+correctAnswer2+".");
        JOptionPane.showMessageDialog(null, "Your third answer is "+qIO.getAnswer3()+". The correct answer is "+correctAnswer3+".");
        JOptionPane.showMessageDialog(null, "Your fourth answer is "+qIO.getAnswer4()+". The correct answer is "+correctAnswer4+".");
        JOptionPane.showMessageDialog(null, "Your fifth answer is "+qIO.getAnswer5()+". The correct answer is "+correctAnswer5+".");
        JOptionPane.showMessageDialog(null, "Your sixth answer is "+qIO.getAnswer6()+". The correct answer is "+correctAnswer6+".");
        JOptionPane.showMessageDialog(null, "Your result is:" +resultPhy+ "%");
          
        
        oiStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex); 
        }
    

        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void bQQ3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQQ3TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bQQ3TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LcPhyQuizOL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PicQueLbl;
    private javax.swing.JLabel bQA2Lbl;
    private javax.swing.JLabel bQA3Lbl;
    private javax.swing.JLabel bQQ1Lbl;
    private javax.swing.JTextField bQQ1TF;
    private javax.swing.JLabel bQQ2Lbl;
    private javax.swing.JTextField bQQ2TF;
    private javax.swing.JLabel bQQ3Lbl;
    private javax.swing.JTextField bQQ3TF;
    private javax.swing.JLabel bQa1Lbl;
    private javax.swing.JButton backQuiz;
    private javax.swing.JLabel basicQuestionLbl;
    private javax.swing.JLabel basicQuestionLbl1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel expTitleLbl2;
    private javax.swing.JButton homeQuiz;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mCQ1Lbl;
    private javax.swing.JLabel pQA1Lbl;
    private javax.swing.JLabel pQA2Lbl;
    private javax.swing.JLabel pQA3Lbl;
    private javax.swing.JLabel pQImage1Lbl;
    private javax.swing.JLabel pQImage2Lbl;
    private javax.swing.JLabel pQImage3Lbl;
    private javax.swing.JLabel pQImage4Lbl;
    private javax.swing.JLabel pQQ1Lbl;
    private javax.swing.JTextField pQQ1TF;
    private javax.swing.JLabel pQQ2Lbl;
    private javax.swing.JTextField pQQ2TF;
    private javax.swing.JLabel pQQ3Lbl;
    private javax.swing.JTextField pQQ3TF;
    private javax.swing.JLabel pic1Lbl;
    private javax.swing.JLabel pic2Lbl;
    private javax.swing.JLabel pic3Lbl;
    private javax.swing.JLabel pic4Lbl;
    private javax.swing.JPanel quiz;
    private javax.swing.JLabel quizLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

}
