/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author caoimhemalone
 */
public class LcPhyQuizHL extends javax.swing.JFrame {
    String question, pQ, answer, answer1, answer2, answer3, answer4, answer5, answer6, correctAnswer, correctAnswer1, correctAnswer2, correctAnswer3, correctAnswer4, correctAnswer5, correctAnswer6;
    double resultPhy = 0.0;
    double markPhy = 0.0;
    
       ArrayList<Quiz> arrQ;
       ArrayList<Quiz> arrAns;
    /**
     * Creates new form LcPhyQuizHL
     */
    public LcPhyQuizHL() {
        initComponents();
        
        arrQ = new ArrayList<>();
        arrAns = new ArrayList<>();
       
        
        Quiz q7 = new Quiz();
        q7.setQuestion("<html>Question 1: Power is measured in?</html>");
        q7.setAnswer1("");
        arrQ.add(q7);
        
        Quiz q8 = new Quiz();
        q8.setQuestion("<html>Question 2: Sound cannot travel through a ______. </html>");      
        q8.setAnswer2("");
        arrQ.add(q8);
        
        Quiz q9 = new Quiz();
        q9.setQuestion("<html> Question 3: Conduction of heat only happens in a ______.</html>");
        q9.setAnswer3("");
        arrQ.add(q9);
        
        Quiz q10 = new Quiz();
        q10.setPQ("<html> The sun is 696,000 km in radius. True or false?</html>");
        q10.setAnswer4("");
        arrQ.add(q10);
        
        
        Quiz q11 = new Quiz();
        q11.setPQ("<html> What is the last name of the first person to land on the moon? </html>");
        q11.setAnswer5("");
        arrQ.add(q11);
        
        Quiz q12 = new Quiz();
        q12.setPQ("<html> Which picture shows the object that is not a planet? Type 'Picture+number with no spaces' </html>");
        q12.setAnswer6("");
        arrQ.add(q12);
        
        
        
        bQQ1Lbl.setText(q7.getQuestion());
        bQQ2Lbl.setText(q8.getQuestion());
        bQQ3Lbl.setText(q9.getQuestion());
        
        pQQ1Lbl.setText(q10.getPQ());
        pQQ2Lbl.setText(q11.getPQ());
        pQQ3Lbl.setText(q12.getPQ());
        
        correctAnswer1 = "Watts";
        correctAnswer2 = "Vacuum";
        correctAnswer3 = "Solid";
        correctAnswer4 = "True";
        correctAnswer5 = "Armstrong";
        correctAnswer6 = "Picture1";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        quiz = new javax.swing.JPanel();
        quizLbl = new javax.swing.JLabel();
        bQQ1Lbl = new javax.swing.JLabel();
        bQQ1TF = new javax.swing.JTextField();
        bQQ2Lbl = new javax.swing.JLabel();
        bQQ2TF = new javax.swing.JTextField();
        bQQ3Lbl = new javax.swing.JLabel();
        bQQ3TF = new javax.swing.JTextField();
        PicQueLbl = new javax.swing.JLabel();
        pQQ1Lbl = new javax.swing.JLabel();
        pQQ1TF = new javax.swing.JTextField();
        pQQ2Lbl = new javax.swing.JLabel();
        pQQ2TF = new javax.swing.JTextField();
        pQQ3Lbl = new javax.swing.JLabel();
        pQQ3TF = new javax.swing.JTextField();
        basicQuestionLbl = new javax.swing.JLabel();
        mCQ1Lbl = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        homeQuiz = new javax.swing.JButton();
        backQuiz = new javax.swing.JButton();
        pQImage1Lbl = new javax.swing.JLabel();
        pQImage2Lbl = new javax.swing.JLabel();
        pQImage3Lbl = new javax.swing.JLabel();
        pQImage4Lbl = new javax.swing.JLabel();
        bQa1Lbl = new javax.swing.JLabel();
        basicQuestionLbl1 = new javax.swing.JLabel();
        bQA2Lbl = new javax.swing.JLabel();
        bQA3Lbl = new javax.swing.JLabel();
        pic1Lbl = new javax.swing.JLabel();
        pic2Lbl = new javax.swing.JLabel();
        pic3Lbl = new javax.swing.JLabel();
        pic4Lbl = new javax.swing.JLabel();
        pQA1Lbl = new javax.swing.JLabel();
        pQA2Lbl = new javax.swing.JLabel();
        pQA3Lbl = new javax.swing.JLabel();
        expTitleLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 398));

        quiz.setBackground(new java.awt.Color(0, 0, 102));

        quizLbl.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        quizLbl.setForeground(new java.awt.Color(255, 255, 0));
        quizLbl.setText("Quiz");

        bQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ1Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ1TF.setPreferredSize(new java.awt.Dimension(171, 28));

        bQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ2Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        bQQ3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        bQQ3Lbl.setPreferredSize(new java.awt.Dimension(0, 253));

        bQQ3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQQ3TFActionPerformed(evt);
            }
        });

        PicQueLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        PicQueLbl.setForeground(new java.awt.Color(255, 255, 0));
        PicQueLbl.setText("Picture Question");

        pQQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ1Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        pQQ2Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ2Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        pQQ3Lbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pQQ3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pQQ3Lbl.setPreferredSize(new java.awt.Dimension(0, 206));

        basicQuestionLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        basicQuestionLbl.setForeground(new java.awt.Color(255, 255, 0));
        basicQuestionLbl.setText("Basic Question");

        mCQ1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(255, 255, 255));
        resetBtn.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        homeQuiz.setBackground(new java.awt.Color(255, 255, 255));
        homeQuiz.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        homeQuiz.setText("Home");
        homeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeQuizActionPerformed(evt);
            }
        });

        backQuiz.setBackground(new java.awt.Color(255, 255, 255));
        backQuiz.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        backQuiz.setText("<-- Back");
        backQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQuizActionPerformed(evt);
            }
        });

        pQImage1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sun.png"))); // NOI18N

        pQImage2Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/moon.png"))); // NOI18N

        pQImage3Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/saturn.png"))); // NOI18N

        pQImage4Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/mars.png"))); // NOI18N

        bQa1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQa1Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQa1Lbl.setText("Answer:");

        basicQuestionLbl1.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        basicQuestionLbl1.setForeground(new java.awt.Color(255, 255, 0));
        basicQuestionLbl1.setText("Please give one word answers.");

        bQA2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQA2Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQA2Lbl.setText("Answer:");

        bQA3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bQA3Lbl.setForeground(new java.awt.Color(255, 255, 0));
        bQA3Lbl.setText("Answer:");

        pic1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pic1Lbl.setText("Picture1");

        pic2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pic2Lbl.setText("Picture2");

        pic3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pic3Lbl.setText("Picture3");

        pic4Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pic4Lbl.setForeground(new java.awt.Color(255, 255, 255));
        pic4Lbl.setText("Picture4");

        pQA1Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA1Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA1Lbl.setText("Answer:");

        pQA2Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA2Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA2Lbl.setText("Answer:");

        pQA3Lbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        pQA3Lbl.setForeground(new java.awt.Color(255, 255, 0));
        pQA3Lbl.setText("Answer:");

        expTitleLbl2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        expTitleLbl2.setForeground(new java.awt.Color(255, 255, 0));
        expTitleLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/ScienceAtom.png"))); // NOI18N

        javax.swing.GroupLayout quizLayout = new javax.swing.GroupLayout(quiz);
        quiz.setLayout(quizLayout);
        quizLayout.setHorizontalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(expTitleLbl2)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(quizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basicQuestionLbl1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bQa1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(bQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(PicQueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pic3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(pic4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQA1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(mCQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(basicQuestionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(bQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pQImage1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pQImage3Lbl))
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(pQImage4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(pQImage2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quizLayout.setVerticalGroup(
            quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addComponent(backQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(homeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basicQuestionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(quizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(basicQuestionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(expTitleLbl2))
                .addGap(4, 4, 4)
                .addComponent(bQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bQa1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(bQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(bQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(bQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(PicQueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pQImage2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(pQImage1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizLayout.createSequentialGroup()
                        .addComponent(pic4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pQImage3Lbl)
                            .addComponent(pQImage4Lbl))
                        .addGap(52, 52, 52)
                        .addComponent(pQQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pQA1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pQQ1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(pQQ2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(pQA2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(pQQ2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mCQ1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(pQQ3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pQA3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pQQ3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pic3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(quiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bQQ3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQQ3TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bQQ3TFActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        answer1 = bQQ1TF.getText();
        answer2 = bQQ2TF.getText();
        answer3 = bQQ3TF.getText();
        answer4 = pQQ1TF.getText();
        answer5 = pQQ2TF.getText();
        answer6 = pQQ3TF.getText();

        Quiz q13 = new Quiz();

        q13.setAnswer1(answer1);
        q13.setAnswer2(answer2);
        q13.setAnswer3(answer3);
        q13.setAnswer4(answer4);
        q13.setAnswer5(answer5);
        q13.setAnswer6(answer6);

        q13.setCorrectAnswer1(correctAnswer1);
        q13.setCorrectAnswer2(correctAnswer2);
        q13.setCorrectAnswer3(correctAnswer3);
        q13.setCorrectAnswer4(correctAnswer5);
        q13.setCorrectAnswer5(correctAnswer6);

        

        if(answer1.equalsIgnoreCase(correctAnswer1)){
            markPhy = markPhy +1;
        }
        if(answer2.equalsIgnoreCase(correctAnswer2)){
            markPhy = markPhy +1;
        }
        if(answer3.equalsIgnoreCase(correctAnswer3)){
            markPhy = markPhy +1;
        }
        if(answer4.equalsIgnoreCase(correctAnswer4)){
            markPhy = markPhy +1;
        }
        if(answer5.equalsIgnoreCase(correctAnswer5)){
            markPhy = markPhy +1;
        }
        if(answer6.equalsIgnoreCase(correctAnswer6)){
            markPhy = markPhy+1;
        }

        if(markPhy == 1){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy ==2){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 3){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 4){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 5){
            resultPhy = ((markPhy*100)/6);
        }
        else if(markPhy == 6){
            resultPhy = ((markPhy*100)/6);
        }


        dispose();
        new LcPhyHL().setVisible(true);
        
                File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("outputQuizHL.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(q13);
            
            oStream.close();
        }
        
        catch(IOException e){
            System.out.println(e);
        }
        
        File inFile;
        FileInputStream fiStream;
        ObjectInputStream oiStream;
        
        try{
            inFile = new File("outputQuizHL.data");
            fiStream = new FileInputStream(inFile);
            oiStream = new ObjectInputStream(fiStream);
            
            
            Quiz qIO = (Quiz)oiStream.readObject();
            
             
        JOptionPane.showMessageDialog(null, "Your first answer is " +qIO.getAnswer1()+ ". The correct answer is "+correctAnswer1+".");
        JOptionPane.showMessageDialog(null, "Your second answer is " +qIO.getAnswer2()+". The correct answer is "+correctAnswer2+".");
        JOptionPane.showMessageDialog(null, "Your third answer is "+qIO.getAnswer3()+". The correct answer is "+correctAnswer3+".");
        JOptionPane.showMessageDialog(null, "Your fourth answer is "+qIO.getAnswer4()+". The correct answer is "+correctAnswer4+".");
        JOptionPane.showMessageDialog(null, "Your fifth answer is "+qIO.getAnswer5()+". The correct answer is "+correctAnswer5+".");
        JOptionPane.showMessageDialog(null, "Your sixth answer is "+qIO.getAnswer6()+". The correct answer is "+correctAnswer6+".");
        JOptionPane.showMessageDialog(null, "Your result is:" +resultPhy+ "%");
          
        
        oiStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex); 
        }

    }//GEN-LAST:event_submitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        bQQ1TF.setText("");
        bQQ2TF.setText("");
        bQQ3TF.setText("");

        pQQ1TF.setText("");
        pQQ2TF.setText("");
        pQQ3TF.setText("");

    }//GEN-LAST:event_resetBtnActionPerformed

    private void homeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeQuizActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeQuizActionPerformed

    private void backQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQuizActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyHL().setVisible(true);
    }//GEN-LAST:event_backQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcPhyQuizHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcPhyQuizHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcPhyQuizHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcPhyQuizHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcPhyQuizHL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PicQueLbl;
    private javax.swing.JLabel bQA2Lbl;
    private javax.swing.JLabel bQA3Lbl;
    private javax.swing.JLabel bQQ1Lbl;
    private javax.swing.JTextField bQQ1TF;
    private javax.swing.JLabel bQQ2Lbl;
    private javax.swing.JTextField bQQ2TF;
    private javax.swing.JLabel bQQ3Lbl;
    private javax.swing.JTextField bQQ3TF;
    private javax.swing.JLabel bQa1Lbl;
    private javax.swing.JButton backQuiz;
    private javax.swing.JLabel basicQuestionLbl;
    private javax.swing.JLabel basicQuestionLbl1;
    private javax.swing.JLabel expTitleLbl2;
    private javax.swing.JButton homeQuiz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mCQ1Lbl;
    private javax.swing.JLabel pQA1Lbl;
    private javax.swing.JLabel pQA2Lbl;
    private javax.swing.JLabel pQA3Lbl;
    private javax.swing.JLabel pQImage1Lbl;
    private javax.swing.JLabel pQImage2Lbl;
    private javax.swing.JLabel pQImage3Lbl;
    private javax.swing.JLabel pQImage4Lbl;
    private javax.swing.JLabel pQQ1Lbl;
    private javax.swing.JTextField pQQ1TF;
    private javax.swing.JLabel pQQ2Lbl;
    private javax.swing.JTextField pQQ2TF;
    private javax.swing.JLabel pQQ3Lbl;
    private javax.swing.JTextField pQQ3TF;
    private javax.swing.JLabel pic1Lbl;
    private javax.swing.JLabel pic2Lbl;
    private javax.swing.JLabel pic3Lbl;
    private javax.swing.JLabel pic4Lbl;
    private javax.swing.JPanel quiz;
    private javax.swing.JLabel quizLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
