/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


/**
 *
 * @author caoimhemalone
 */
public class LcPhyHL extends javax.swing.JFrame {

    /**
     * Creates new form lcPhy
     */
    public LcPhyHL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCPhyLbl = new javax.swing.JLabel();
        modDesBtn = new javax.swing.JButton();
        markSchBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        expBtn = new javax.swing.JButton();
        homelcPhy = new javax.swing.JButton();
        backlcPhy = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        lCPhyLbl.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lCPhyLbl.setForeground(new java.awt.Color(255, 255, 0));
        lCPhyLbl.setText("Leaving Cert Physics Higher Level ");
        getContentPane().add(lCPhyLbl);
        lCPhyLbl.setBounds(110, 100, 423, 36);

        modDesBtn.setBackground(new java.awt.Color(255, 255, 0));
        modDesBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        modDesBtn.setText("Module Description");
        modDesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(modDesBtn);
        modDesBtn.setBounds(134, 158, 356, 87);

        markSchBtn.setBackground(new java.awt.Color(255, 255, 0));
        markSchBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        markSchBtn.setText("Marking Scheme");
        markSchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markSchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(markSchBtn);
        markSchBtn.setBounds(134, 263, 356, 87);

        quizBtn.setBackground(new java.awt.Color(255, 255, 0));
        quizBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        quizBtn.setText("Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quizBtn);
        quizBtn.setBounds(134, 368, 356, 87);

        expBtn.setBackground(new java.awt.Color(255, 255, 0));
        expBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        expBtn.setText("Experiments");
        expBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expBtnActionPerformed(evt);
            }
        });
        getContentPane().add(expBtn);
        expBtn.setBounds(134, 473, 356, 87);

        homelcPhy.setBackground(new java.awt.Color(255, 255, 255));
        homelcPhy.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        homelcPhy.setText("Home");
        homelcPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homelcPhyActionPerformed(evt);
            }
        });
        getContentPane().add(homelcPhy);
        homelcPhy.setBounds(6, 6, 122, 65);

        backlcPhy.setBackground(new java.awt.Color(255, 255, 255));
        backlcPhy.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        backlcPhy.setText("<-- Back");
        backlcPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backlcPhyActionPerformed(evt);
            }
        });
        getContentPane().add(backlcPhy);
        backlcPhy.setBounds(10, 580, 168, 84);

        background2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        background2.setForeground(new java.awt.Color(255, 255, 0));
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/background1.jpg"))); // NOI18N
        getContentPane().add(background2);
        background2.setBounds(0, 0, 610, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homelcPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homelcPhyActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_homelcPhyActionPerformed

    private void backlcPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backlcPhyActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyOption().setVisible(true);
    }//GEN-LAST:event_backlcPhyActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyQuizHL().setVisible(true);
    }//GEN-LAST:event_quizBtnActionPerformed

    private void modDesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDesBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyMD().setVisible(true);
    }//GEN-LAST:event_modDesBtnActionPerformed

    private void markSchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markSchBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyMS().setVisible(true);
    }//GEN-LAST:event_markSchBtnActionPerformed

    private void expBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyExp().setVisible(true);
    }//GEN-LAST:event_expBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcPhyHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcPhyHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcPhyHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcPhyHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcPhyHL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background2;
    private javax.swing.JButton backlcPhy;
    private javax.swing.JButton expBtn;
    private javax.swing.JButton homelcPhy;
    private javax.swing.JLabel lCPhyLbl;
    private javax.swing.JButton markSchBtn;
    private javax.swing.JButton modDesBtn;
    private javax.swing.JButton quizBtn;
    // End of variables declaration//GEN-END:variables
}
