/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;



/**
 *
 * @author caoimhemalone
 */
public class LcPhyMD extends javax.swing.JFrame {
    
    //String name, description, duration;
    
    

    /**
     * Creates new form ModuleDescriptorPhy
     */
    public LcPhyMD() {
        initComponents();
        nameLbl.setText("Leaving Cert Physics");
        durationLbl.setText("2 Years");
        desTF.setText("1.Mechanics \n 2.Temperature \n 3.Heat \n 4.Waves \n 5.Vibrations & Sounds \n 6.Light \n 7.Electricity \n 8.Modern Physics \n 9a.Option1: Particle Physics \n 9b.Option2: Applied Electricity");
        //nameLbl.setText(name);
        //durationLbl.setText(duration);
        //desTF.setText(description);
        
        
        
        //name = ("Leaving Cert Physics");
        //duration = ();
        //description=("1.Mechanics \n 2.Temperature \n 3.Heat \n 4.Waves \n 5.Vibrations & Sounds \n 6.Light \n 7.Electricity \n 8.Modern Physics \n 9a.Option1: Particle Physics \n 9b.Option2: Applied Electricity");

        ModuleDescription m = new ModuleDescription();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeModDesPhy = new javax.swing.JButton();
        backModDesPhy = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        moduleNameLbl = new javax.swing.JLabel();
        moduleDurationLbl = new javax.swing.JLabel();
        moduleDesLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        durationLbl = new javax.swing.JLabel();
        desTF = new javax.swing.JTextArea();
        backExpPhy1 = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        homeModDesPhy.setBackground(new java.awt.Color(255, 255, 255));
        homeModDesPhy.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        homeModDesPhy.setText("Home");
        homeModDesPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeModDesPhyActionPerformed(evt);
            }
        });
        getContentPane().add(homeModDesPhy);
        homeModDesPhy.setBounds(6, 6, 126, 66);

        backModDesPhy.setBackground(new java.awt.Color(255, 255, 255));
        backModDesPhy.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backModDesPhy.setText("Back to HL Phy");
        backModDesPhy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backModDesPhyActionPerformed(evt);
            }
        });
        getContentPane().add(backModDesPhy);
        backModDesPhy.setBounds(387, 13, 160, 57);

        titleLbl.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 0));
        titleLbl.setText("Module Description");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(164, 165, 266, 61);

        moduleNameLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        moduleNameLbl.setForeground(new java.awt.Color(255, 255, 0));
        moduleNameLbl.setText("Module Name:");
        getContentPane().add(moduleNameLbl);
        moduleNameLbl.setBounds(30, 240, 135, 46);

        moduleDurationLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        moduleDurationLbl.setForeground(new java.awt.Color(255, 255, 0));
        moduleDurationLbl.setText("Duration:");
        getContentPane().add(moduleDurationLbl);
        moduleDurationLbl.setBounds(30, 310, 135, 53);

        moduleDesLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        moduleDesLbl.setForeground(new java.awt.Color(255, 255, 0));
        moduleDesLbl.setText("Description of Module:");
        getContentPane().add(moduleDesLbl);
        moduleDesLbl.setBounds(30, 370, 261, 55);

        nameLbl.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nameLbl);
        nameLbl.setBounds(178, 242, 410, 46);

        durationLbl.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        durationLbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(durationLbl);
        durationLbl.setBounds(180, 310, 399, 48);

        desTF.setEditable(false);
        desTF.setColumns(20);
        desTF.setFont(new java.awt.Font("Lucida Calligraphy", 0, 16)); // NOI18N
        desTF.setRows(5);
        getContentPane().add(desTF);
        desTF.setBounds(30, 430, 539, 240);

        backExpPhy1.setBackground(new java.awt.Color(255, 255, 255));
        backExpPhy1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backExpPhy1.setText("Back to OL Phy");
        backExpPhy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backExpPhy1ActionPerformed(evt);
            }
        });
        getContentPane().add(backExpPhy1);
        backExpPhy1.setBounds(387, 90, 160, 57);

        background4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        background4.setForeground(new java.awt.Color(255, 255, 0));
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/background1.jpg"))); // NOI18N
        getContentPane().add(background4);
        background4.setBounds(0, -10, 610, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeModDesPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeModDesPhyActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeModDesPhyActionPerformed

    private void backModDesPhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backModDesPhyActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyHL().setVisible(true);
    }//GEN-LAST:event_backModDesPhyActionPerformed

    private void backExpPhy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backExpPhy1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyOL().setVisible(true);
    }//GEN-LAST:event_backExpPhy1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcPhyMD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backExpPhy1;
    private javax.swing.JButton backModDesPhy;
    private javax.swing.JLabel background4;
    private javax.swing.JTextArea desTF;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JButton homeModDesPhy;
    private javax.swing.JLabel moduleDesLbl;
    private javax.swing.JLabel moduleDurationLbl;
    private javax.swing.JLabel moduleNameLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
