/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;




/**
 *
 * @author caoimhemalone
 */
public class LcPhyOption extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public LcPhyOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelLbl = new javax.swing.JLabel();
        ordinaryLbl = new javax.swing.JButton();
        higherLbl = new javax.swing.JButton();
        homeLevel = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        background6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        levelLbl.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        levelLbl.setForeground(new java.awt.Color(255, 255, 0));
        levelLbl.setText("Leaving Cert Physics");
        getContentPane().add(levelLbl);
        levelLbl.setBounds(170, 100, 279, 75);

        ordinaryLbl.setBackground(new java.awt.Color(255, 255, 0));
        ordinaryLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ordinaryLbl.setText("Ordinary");
        ordinaryLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordinaryLblActionPerformed(evt);
            }
        });
        getContentPane().add(ordinaryLbl);
        ordinaryLbl.setBounds(113, 217, 355, 128);

        higherLbl.setBackground(new java.awt.Color(255, 255, 0));
        higherLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        higherLbl.setText("Higher");
        higherLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherLblActionPerformed(evt);
            }
        });
        getContentPane().add(higherLbl);
        higherLbl.setBounds(113, 379, 355, 129);

        homeLevel.setBackground(new java.awt.Color(255, 255, 255));
        homeLevel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        homeLevel.setText("Home");
        homeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLevelActionPerformed(evt);
            }
        });
        getContentPane().add(homeLevel);
        homeLevel.setBounds(6, 6, 126, 70);

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        backBtn.setText("<-- Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(6, 583, 163, 81);

        background6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        background6.setForeground(new java.awt.Color(255, 255, 0));
        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/background1.jpg"))); // NOI18N
        getContentPane().add(background6);
        background6.setBounds(-1, -5, 610, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordinaryLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordinaryLblActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyOL().setVisible(true);
    }//GEN-LAST:event_ordinaryLblActionPerformed

    private void higherLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherLblActionPerformed
        // TODO add your handling code here:
        dispose();
        new LcPhyHL().setVisible(true);
    }//GEN-LAST:event_higherLblActionPerformed

    private void homeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLevelActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_homeLevelActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new GUI().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LcPhyOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LcPhyOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LcPhyOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LcPhyOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LcPhyOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background6;
    private javax.swing.JButton higherLbl;
    private javax.swing.JButton homeLevel;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JButton ordinaryLbl;
    // End of variables declaration//GEN-END:variables
}
